name: chacha_rng
description: PRNG based on the ChaCha stream cipher
version: 0.1.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  benchmark_harness: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
